# subworlflow: data-management
#
# Contributors: YOUR NAME

import glob, os

# --- Importing Configuration Files --- #

configfile: "config.yaml"


# --- Dictionaries --- #

# --- Build Rules --- #

rule gen_regression_vars:
    input:
        script = config["src_data_mgt"] + "gen_reg_vars.R",
        data   = config["out_data"] + "mrw_renamed.csv",
        params = config["src_model_specs"] + "solow_param.json",
    output:
        data = config["out_data"] + "mrw_complete.csv",
    log:
        config["log"] + "data_cleaning/gen_reg_vars.txt"
    shell:
        "{runR} {input.script} --data {input.data} --param {input.params} \
            --out {output.data} \
            > {log} {logAll}"

rule rename_vars:
    input:
        script = config["src_data_mgt"] + "rename_variables.R",
        data   = config["src_data"] + "mrw.dta",
    output:
        data = config["out_data"] + "mrw_renamed.csv",
    log:
        config["log"] + "data_cleaning/rename_variables.txt"
    shell:
        "{runR} {input.script} --data {input.data} --out {output.data} \
            > {log} {logAll}"
