# subworlflow: figures
#
# Contributors: YOUR NAME

import glob, os

# --- Importing Configuration Files --- #

configfile: "config.yaml"

# --- Dictionaries --- #

# --- Sub Workflows --- #
subworkflow data_mgt:
    workdir: config["sub2root"] + config["ROOT"]
    snakefile: config["sub2root"] + config["src_data_mgt"] + "Snakefile"

# --- Build Rules --- #

rule uncond_conv:
    input:
        script = config["src_figures"] + "unconditional_convergence.R",
        data   = data_mgt(config["out_data"] + "mrw_complete.csv"),
        subset = config["src_data_specs"] + "subset_intermediate.json"
    output:
        fig = config["out"] + "figures/unconditional_convergence.pdf",
    log:
        config["log"] + "figures/unconditional_convergence.txt"
    shell:
        "{runR} {input.script} \
            --data {input.data} \
            --subset {input.subset} \
            --out {output.fig} \
            > {log} {logAll}"
