# subworkflow: figures
#
# Contributors: @lachlandeer, @julianlanger

# --- Importing Configuration Files --- #

configfile: "paths.yaml"

# --- Dictionaries --- #

# --- Sub Workflows --- #
subworkflow data_mgt:
    workdir: config["sub2root"] + config["ROOT"]
    snakefile: config["sub2root"] + config["src_data_mgt"] + "Snakefile"

# --- Build Rules --- #

rule make_figs:
    input:
        expand(config["out_figures"] + "{iFigure}.pdf",
                iFigure = PLOTS)

rule figures:
    input:
        script = config["src_figures"] + "{iFigure}.R",
        data   = data_mgt(config["out_data"] + "mrw_complete.csv"),
        subset = config["src_data_specs"] + "subset_intermediate.json"
    output:
        fig = config["out_figures"] + "{iFigure}.pdf",
    log:
        config["log"] + "figures/{iFigure}.txt"
    shell:
        "{runR} {input.script} \
            --data {input.data} \
            --subset {input.subset} \
            --out {output.fig} \
            > {log} {logAll}"
