# subworlflow: tables
#
# Contributors: YOUR NAME

import glob, os

# --- Importing Configuration Files --- #

configfile: "config.yaml"

# --- Dictionaries --- #

# --- Sub Workflows --- #
subworkflow analysis:
    workdir: config["sub2root"] + config["ROOT"]
    snakefile: config["sub2root"] + config["src_analysis"] + "Snakefile"

# --- Build Rules --- #

rule textbook_solow:
    input:
        script = config["src_tables"] + "tab01_textbook_solow.R",
        models = analysis(expand(config["out_analysis"] +
                            "{iModel}_ols_{iSubset}.rds",
                            iModel = MODELS,
                            iSubset = DATA_SUBSET)),
    params:
        filepath   = config["out_analysis"],
        model_expr = "model_solow*.rds"
    output:
        table = config["out_tables"] + "tab01_textbook_solow.tex",
    log:
        config["log"] + "tables/tab01_textbook_solow.txt"
    shell:
        "{runR} {input.script} \
            --filepath {params.filepath} \
            --models {params.model_expr} \
            --out {output.table} \
            > {log} {logAll}"
