# subworlflow: tables
#
# Contributors: YOUR NAME

import glob, os

# --- Importing Configuration Files --- #

configfile: "config.yaml"

# --- Dictionaries --- #

# --- Sub Workflows --- #
subworkflow analysis:
    workdir: config["sub2root"] + config["ROOT"]
    snakefile: config["sub2root"] + config["src_analysis"] + "Snakefile"

# --- Build Rules --- #
