# subworlflow: analysis
#
# Contributors: YOUR NAME

import glob, os

# --- Importing Configuration Files --- #

configfile: "config.yaml"

# --- Dictionaries --- #

# --- Sub Workflows --- #
subworkflow data_mgt:
    workdir: "../../" + config["ROOT"]
    snakefile: "../../" + config["src_data_mgt"] + "Snakefile"

# --- Build Rules --- #

rule ols_model:
    input:
        script = config["src_analysis"] + "estimate_ols_model.R",
        data   = data_cleaning(config["out_data"] + "mrw_complete.csv"),
        model  = config["src_model_specs"] + "solow.json",
        subset = config["src_model_specs"] + "nonoil.json"
    output:
        model_est = config["out_analysis"] + "ols.rds",
    log:
        config["log"] + "analysis/ols_model.txt"
    shell:
        "{runR} {input.script} --data {input.data} --model {input.model} \
            --subset {input.subset} --out {output.model_est} \
            > {log} {logAll}"
