# subworkflow: paper
#
# rticle-style: asa
#
# contributors: @lachlandeer, @julianlanger

import glob, os

# --- Importing Configuration Files --- #
configfile: "../../" + "config.yaml"

# --- Sub Workflow Dependencies --- #
subworkflow figures:
    workdir:  config["sub2root"] + config["ROOT"]
    snakefile: config["sub2root"] + config["src_figures"] + "Snakefile"

subworkflow tables:
    workdir:   config["sub2root"] + config["ROOT"]
    snakefile: config["sub2root"] + config["src_tables"] + "Snakefile"

# --- Dictionaries --- #
RMD_FILES  = glob.glob("*.Rmd")
YAML_FILES = glob.glob("*.yml")
CSS_FILES  = glob.glob("*.css")
BIB_FILES  = glob.glob("*.bib")
TEX_FILES  = glob.glob("*.tex")

# --- Variable Declarations ---- #
runR = "Rscript --no-save --no-restore --verbose"
logAll = "2>&1"

# --- Build Rules --- #

rule all:
    input:
        pdf  = "_book/my_article.pdf",
    output:
        pdf  = config["sub2root"] + PROJ_NAME + ".pdf",
    shell:
        "cp {input.pdf} {output.pdf}"

rule pdf:
    input:
        text_files = RMD_FILES,
        yaml_files = YAML_FILES,
        biblo      = BIB_FILES,
        tex_style  = TEX_FILES,
        tables     = tables(expand(config["out_tables"] +
                            "{iTable}.tex",
                            iTable = TABLES)),
        figures = figures(expand(config["out_figures"] +
                            "{iPlot}.pdf",
                            iPlot = PLOTS)),
        runner     = "build_pdfbook.R"
    output:
        "_book/" + "my_article.pdf"
    log:
        "../../" + config["log"] + "paper/build_pdf.Rout"
    shell:
        "{runR} {input.runner} > {log} {logAll}"


rule clean:
    shell:
        "rm -rf _book/* bookdown_files/* *.pdf *.html"
